### PR TITLE
Added function plotDAbeeswarm

### PR DESCRIPTION
**Pull request by emdann**
Added function to visualize DA results as a beeswarm, to group nhood by some label e.g. cell types

Example:
```
plotDAbeeswarm(da.res, group.by = "annotation_lineage")
```
example (1)

### CODE REVIEW

**Comment by emdann** [comment]
+ small fixes and cleaning of `plotNhoods.R`

**Comment by MikeDMorgan** [comment]
Travis error: ``` undefined exports: plotMiloReducedDim``` <- is this a hangover from some previous changes?

**Comment by emdann** [comment]
ups, no I just deleted those old functions and forgot to update NAMESPACE. I'm fixing this.

**Comment by MikeDMorgan** [comment]
This is fine to merge - Travis is just complaining about R versions.

**Pull request merged**
