### PR TITLE
spatialGraphFDR now uses k-distance FDR weighting using the kth NN

### PR DESCRIPTION
**Pull request by MikeDMorgan**
The previous implementation of `graphSpatialFDR` with 'k-distance' used the maximum within-neighbourhood distance to calculate the weighting for the spatial FDR. Strictly, this should use the same value of `k` as for graph building.

The 'k-distance' FDR weighting now uses the distance to the kth NN within each neighbourhood to compute the weighted FDR. The original behaviour, i.e. using the _maximum_ within-neighbourhood distance can be accessed by passing `fdr.weighting="max"`.

To achieve this there is now a hidden slot `.k`, that stores the value of k used for graph building.

### CODE REVIEW

**Comment by emdann** [comment]
Great addition Mike, does this change the FDR correction significantly?

**Comment by MikeDMorgan** [comment]
> Great addition Mike, does this change the FDR correction significantly?

On the test discrete simulation they give the same results. Not run on the broader simulations yet.

image

**Comment by PedroMilanezAlmeida** [comment]
Hey @MikeDMorgan,

Thanks a lot for making and keeping the package.

Given that the default behavior of ```spatialGraphFDR``` is to use the k-th distance as weight, I was wondering if ```calcNhoodDistance``` could calculate only the within-neighborhood knn distances rather than all distances. Would that maybe make it faster?

**Comment by PedroMilanezAlmeida** [comment]
@MikeDMorgan I found this will be done if distances are not supplied 😊

**Pull request merged**
