### PR TITLE
[DRAFT] Splitting nhood grouping from DGE testing

### PR DESCRIPTION
**Pull request by emdann**
A Frequently Requested update: fixing the downstream analysis/differential expression testing by splitting the nhood grouping and the testing within/between nhood groups + new plotting functions.

**Main updates to grouping strategy:** (Changes in [`.group_nhoods_by_adjancency`](https://github.com/MarioniLab/miloR/blob/75aa63f44acc10edae50c2a0e6924609dffa8cd8/R/groupNhoods.R#L86))
- no longer keeping just groups of DA neighbourhoods
- changed the `lfc.threshold` parameter to `max.lfc.delta`: instead of removing all edges from nhoods with `da.res$logFC < lfc.threshold`, now we compute the delta in logFC between all neighbourhoods, and remove edges if the delta is higher than `max.lfc.delta` (so lower `max.lfc.delta`, smaller communities). Just removing all edges resulted in weird singletons with community detection.

For now I have kept `findNhoodMarkers` unchanged to avoid breaking all the vignettes and user analyses, even though `.group_nhoods_by_adjancency` has been changed.

Related issues: https://github.com/MarioniLab/miloR/issues/115 https://github.com/MarioniLab/miloR/issues/103

**Example workflow**

I have my Milo object and DA results
```
> milo
class: Milo 
dim: 23434 64018 
metadata(0):
assays(2): counts logcounts
rownames(23434): ENSMUSG00000051951 ENSMUSG00000102343 ... ENSMUSG00000063897 ENSMUSG00000095742
rowData names(2): ENSEMBL SYMBOL
colnames(64018): cell_7625 cell_7626 ... cell_139330 cell_139331
colData names(28): cell barcode ... synth_batches predDA_milo
reducedDimNames(6): pca.corrected umap ... pca_batch umap_batch
altExpNames(0):
nhoods dimensions(2): 64018 3956
nhoodCounts dimensions(2): 3956 6
nhoodDistances dimension(1): 3956
graph names(1): graph
nhoodIndex names(1): 3956
nhoodExpression dimension(2): 1 1
nhoodReducedDim names(0):
nhoodGraph names(1): nhoodGraph
nhoodAdjacency dimension(2): 3956 3956

> head(da.res)
   logFC logCPM      F   PValue      FDR Nhood SpatialFDR
1 -0.109   21.6  0.409 5.23e-01 7.56e-01     1   7.66e-01
2 -0.579   21.6 10.667 1.09e-03 1.00e-02     2   1.01e-02
3 -0.351   21.0  2.695 1.01e-01 2.96e-01     3   3.05e-01
4 -1.677   21.0 52.106 5.74e-13 6.31e-11     4   5.86e-11
5 -0.343   20.3  1.507 2.20e-01 4.70e-01     5   4.82e-01
6 -0.247   20.9  1.209 2.72e-01 5.31e-01     6   5.42e-01
```

I run `buildNhoodGraph` to create the neighbourhood adjacency matrix (stored in `nhoodAdjacency(milo)`)
```
milo <- buildNhoodGraph(milo)
plotNhoodGraphDA(milo, da.res, alpha = 0.1)
```

Partition nhoods into groups

```{r}
> da.res <- groupNhoods(milo, da.res, max.lfc.delta = 1)
> head(da.res)
   logFC logCPM      F   PValue      FDR Nhood SpatialFDR NhoodGroup
1 -0.109   21.6  0.409 5.23e-01 7.56e-01     1   7.66e-01         10
2 -0.579   21.6 10.667 1.09e-03 1.00e-02     2   1.01e-02          9
3 -0.351   21.0  2.695 1.01e-01 2.96e-01     3   3.05e-01          7
4 -1.677   21.0 52.106 5.74e-13 6.31e-11     4   5.86e-11          6
5 -0.343   20.3  1.507 2.20e-01 4.70e-01     5   4.82e-01         12
6 -0.247   20.9  1.209 2.72e-01 5.31e-01     6   5.42e-01          7
```

Visualize the groups
```{r}
plotNhoodGroups(milo, da.res)
```

Find your markers for all groups (one-VS-all test)
```
> nhood_markers <- findNhoodGroupMarkers(milo, da.res, subset.row = rownames(milo)[1:10])
> head(nhood_markers)
                    logFC_10 adj.P.Val_10   logFC_9 adj.P.Val_9   logFC_7 adj.P.Val_7   logFC_6 adj.P.Val_6
ENSMUSG00000025902  0.259396     0.00e+00 -0.131786    8.98e-93 -0.131973   1.76e-209 -0.169383    3.31e-63
ENSMUSG00000033845 -0.230990    7.66e-179 -0.105913    4.43e-28  0.069444    1.90e-46 -0.089946    1.10e-39
ENSMUSG00000025900  0.005088     5.16e-66  0.006753    1.79e-14  0.006732    3.85e-31  0.032260    7.67e-05
ENSMUSG00000033813 -0.088934     7.98e-47  0.056301    1.81e-14 -0.043269    2.16e-11 -0.011141    2.76e-01
ENSMUSG00000025903 -0.048251     2.58e-17  0.022556    1.34e-03  0.000867    2.41e-05  0.000256    8.26e-01
ENSMUSG00000104328  0.000119     2.94e-03  0.000798    1.22e-02 -0.019049    2.65e-05 -0.000196    8.30e-01
                    logFC_12 adj.P.Val_12   logFC_8 adj.P.Val_8 logFC_13 adj.P.Val_13  logFC_11 adj.P.Val_11
ENSMUSG00000025902  0.247366    2.98e-161 -0.108863    8.59e-89 -0.06427     1.35e-26 -0.229843     1.59e-91
ENSMUSG00000033845 -0.114962     5.18e-77 -0.117172    1.71e-47 -0.06161     2.39e-23 -0.074284     8.64e-22
ENSMUSG00000025900  0.060042     1.83e-17  0.030969    1.35e-06  0.05817     7.41e-18  0.073039     5.53e-17
ENSMUSG00000033813 -0.041622     1.53e-10  0.019387    1.34e-03 -0.03706     5.71e-05 -0.002221     7.53e-02
ENSMUSG00000025903 -0.003735     1.34e-05 -0.002380    2.21e-03  0.00289     5.36e-04 -0.000549     3.64e-01
ENSMUSG00000104328 -0.000608     1.14e-01 -0.000419    1.59e-01 -0.00066     6.43e-02 -0.000441     4.19e-01
                     logFC_2 adj.P.Val_2   logFC_4 adj.P.Val_4   logFC_3 adj.P.Val_3  logFC_1 adj.P.Val_1
ENSMUSG00000025902  0.574411    0.00e+00  0.255264   2.08e-148  0.444623    0.00e+00  0.51444    0.00e+00
ENSMUSG00000033845 -0.208080   1.47e-143 -0.086193    1.10e-35 -0.115400    9.70e-64  0.45789    0.00e+00
ENSMUSG00000025900 -0.220371   2.63e-135 -0.081395    4.23e-34  0.106143    5.22e-43  0.45639    0.00e+00
ENSMUSG00000033813 -0.231483    8.37e-87  0.051146    1.93e-11 -0.048013    2.15e-11 -0.39663    0.00e+00
ENSMUSG00000025903 -0.004965    6.01e-06 -0.002557    8.33e-03 -0.003637    1.45e-04 -0.00997    6.06e-30
ENSMUSG00000104328 -0.000923    1.94e-02 -0.000475    3.09e-01 -0.000617    1.56e-01 -0.00103    1.01e-03
                     logFC_5 adj.P.Val_5             GeneID
ENSMUSG00000025902 -0.221340    5.02e-33 ENSMUSG00000033845
ENSMUSG00000033845 -0.084105    3.88e-11 ENSMUSG00000025902
ENSMUSG00000025900  0.073789    1.98e-08 ENSMUSG00000025903
ENSMUSG00000033813 -0.027359    1.20e-01 ENSMUSG00000033813
ENSMUSG00000025903 -0.000374    8.86e-01 ENSMUSG00000104217
ENSMUSG00000104328 -0.000334    8.86e-01 ENSMUSG00000051951
```

Visualize gene expression by group

```
plotNhoodExpressionGroups(milo, da.res, features=nhood_markers$GeneID,
                          subset.nhoods = da.res$NhoodGroup %in% c("9", '11', "4"), scale=TRUE,
                          grid.space = "fixed")
```

The subsetting capabilities can be used to specify the type of test to do, there will be a specific vignette showing what the options are.

Feedback welcome.

### CODE REVIEW

**Comment by emdann** [comment]
TO DO:

- [ ] Tests
- [ ] Update vignettes

**Comment by MikeDMorgan** [comment]
This is excellent @emdann. I wonder, with the `plotNhoodExpressionGroups` (which I think perfectly deals with one of the reviewers comment btw), does it make sense to change the nhood and gene selection refer to the specific nhood groups? This could still use the boolean indexing as already implemented, but might give a nice fast way to access/visualise the marker genes for a set of nhoods, rather than the user having to subset them?

For instance, the syntax could look something like: 
```
plotNhoodExpressionGroups(milo, da.res, group.features=c(4, 9, 11), nhood.groups=c(4, 9, 11),  scale=TRUE, grid.space = "fixed")
```

**Comment by emdann** [comment]
> does it make sense to change the nhood and gene selection refer to the specific nhood groups?

I think even if I added group specific parameters I would still need to keep the current nhood and feature selection parameters for more flexible visualization e.g. if I want to visualize the neighbourhoods from group 1, but only the ones that are significantly DA (because the grouping now doesn't keep a hard split between DA and not DA nhoods), or filter by logFC, or filter genes by variable significance level etc... I'd go for just keeping `features` and `subset.nhoods` with a vignette showing all these options to the user.

**Comment by MikeDMorgan** [comment]
> > does it make sense to change the nhood and gene selection refer to the specific nhood groups?
> 
> I think even if I added group specific parameters I would still need to keep the current nhood and feature selection parameters for more flexible visualization e.g. if I want to visualize the neighbourhoods from group 1, but only the ones that are significantly DA (because the grouping now doesn't keep a hard split between DA and not DA nhoods), or filter by logFC, or filter genes by variable significance level etc... I'd go for just keeping `features` and `subset.nhoods` with a vignette showing all these options to the user.

OK - perhaps we can have extra parameters down the line if users request them in that case.

**Comment by MikeDMorgan** [comment]
The vignettes are the most common cause of build failures. I can turn them off for now, but we do need to fix them before official release.

**Comment by emdann** [comment]
I'm making a new one for this downstream analysis stuff, the others need updating. I would hold off pushing this to master until vignettes are fixed.

**Comment by MikeDMorgan** [comment]
> I'm making a new one for this downstream analysis stuff, the others need updating. I would hold off pushing this to master until vignettes are fixed.

OK - I've switched off the vignette building for now in the actions just to make sure everything else runs fine. Once they are fixed then we can run the full checks properly.

**Comment by emdann** [comment]
The checks have passed!! @MikeDMorgan would you mind checking if you are able to build the vignettes locally?

**Comment by MikeDMorgan** [comment]
> The checks have passed!! @MikeDMorgan would you mind checking if you are able to build the vignettes locally?

First attempt fail - trying again with a tweak.

**Comment by MikeDMorgan** [comment]
> > The checks have passed!! @MikeDMorgan would you mind checking if you are able to build the vignettes locally?
> 
> First attempt fail - trying again with a tweak.
This is the error message:

Error in .group_nhoods_from_adjacency(nhoods(x), nhood.adj = nhoodAdjacency(x),  : 
  Overlap matrix is not symmetric

**Comment by emdann** [comment]
> Error in .group_nhoods_from_adjacency(nhoods(x), nhood.adj = nhoodAdjacency(x), :
Overlap matrix is not symmetric

What dataset are you using?

**Comment by MikeDMorgan** [comment]
> > Error in .group_nhoods_from_adjacency(nhoods(x), nhood.adj = nhoodAdjacency(x), :
> > Overlap matrix is not symmetric
> 
> What dataset are you using?

This is from the vignette building locally on this branch.

**Comment by emdann** [comment]
Are you sure that the old version of `.group_nhoods_from_adjacency` is not loaded to the globalEnv for some reason?

**Comment by MikeDMorgan** [comment]
> Are you sure that the old version of `.group_nhoods_from_adjacency` is not loaded to the globalEnv for some reason?

This is a clean environment, running `R CMD build` either in a new Rstudio session or from the command line.

**Comment by emdann** [comment]
I can't reproduce, building on clean local environment I manage to build with vignettes and no errors. R version?

**Comment by MikeDMorgan** [comment]
4.0.3 - I'll check on the CI cluster as well which is 4.0.2

**Comment by MikeDMorgan** [comment]
> 4.0.3 - I'll check on the CI cluster as well which is 4.0.2

Clean install on the CI cluster - it's an issue with my local environment.

**Comment by MikeDMorgan** [comment]
> > 4.0.3 - I'll check on the CI cluster as well which is 4.0.2
> 
> Clean install on the CI cluster - it's an issue with my local environment.

Confirmed clean build on command line locally - it must be something that is being pulled into the Rstudio session inappropriately. Good to go!

**Pull request merged**
