### PR TITLE
Adding error message for wrong input to constructor

### PR DESCRIPTION
**Pull request by emdann**
First patch to https://github.com/MarioniLab/miloR/issues/242: 
- now if the input is not correct the constructor throws an error message
- TO DO: take feature x cell matrix in input, or should we just change the docs? @MikeDMorgan

### CODE REVIEW

**Comment by MikeDMorgan** [comment]
Thanks for moving on this so quickly @emdann! I think we should test for a matrix-type input and construct the appropriate Milo object - it gives a degree more flexibility, for instance if someone only has a counts matrix available.

**Comment by emdann** [comment]
I'm procrasti-working 👯 
Check if this does the trick, not sure if there is a safer way to check for sparse/non-sparse matrices than
```
is(..., "matrix") | is(..., "Matrix")
```

**Comment by MikeDMorgan** [comment]
> I'm procrasti-working 👯 Check if this does the trick, not sure if there is a safer way to check for sparse/non-sparse matrices than
> 
> ```
> is(..., "matrix") | is(..., "Matrix")
> ```

That should do the trick.

**Comment by emdann** [comment]
The failing check is the usual suspect. If you have no additional comments I'll merge this.

**Comment by MikeDMorgan** [comment]
Yeah - looks good. I should probably try to fix the windows checks at some point.

**Pull request merged**
